name: Run depcheck
description: Analyze npm project dependencies

inputs:
  dir:
    description: 'The directory to run [depcheck](https://github.com/depcheck/depcheck#readme)'
    required: false
    default: '.'
  ignores:
    description: 'Comma separated list of packages to ignore'
    required: false
    default: ''
  version:
    description: 'Version of [depcheck](https://github.com/depcheck/depcheck/tags)'
    required: false
    default: '1.4.3'

outputs:
  result_json:
    description: 'depcheck result object as json'
    value: ${{ steps.depcheck.outputs.result_json }}


runs:
  using: 'composite'
  steps:
    - run: |
        echo "result_json=$(npx --yes depcheck@"${INPUT_VERSION}" --ignores="${INPUT_IGNORES}" "${INPUT_DIR}" --json | jq -Rsa . | sed 's/\\[tn]//g')" >> "$GITHUB_OUTPUT"
      id: depcheck
      shell: bash
      env:
        INPUT_DIR: ${{ inputs.dir }}
        INPUT_IGNORES: ${{ inputs.ignores }}
        INPUT_VERSION: ${{ inputs.version }}
branding:
  icon: check-square
  color: white