name: Check dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      dependencies_matrix: ${{ steps.matrix.outputs.dependencies }}
      devDependencies_matrix: ${{ steps.matrix.outputs.devDependencies }}
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v3
      - name: Check node dependencies
        id: depcheck
        uses: ./.github/actions/depcheck
        with:
          dir: test/
      - id: matrix
        name: Get unused dependencies
        run: |
          dependencies=$(echo ${{ steps.depcheck.outputs.result_json }} | jq '.dependencies' -c)
          echo "dependencies=$dependencies" >> $GITHUB_OUTPUT
          devDependencies=$(echo ${{ steps.depcheck.outputs.result_json }} | jq '.devDependencies' -c)
          echo "devDependencies=$devDependencies" >> $GITHUB_OUTPUT

  cleanup-dependencies:
    needs: [setup]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        value: ${{fromJson(needs.setup.outputs.dependencies_matrix)}}
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v3
      - name: Npm remove
        run: |
          cd test/
          npm remove ${{ matrix.value }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          committer: GitHub <noreply@github.com>
          commit-message: Remove unused dependency ${{ matrix.value }}
          title: Remove unused dependency ${{ matrix.value }}
          body: 
          branch: depcheck/remove-dependency-${{ matrix.value }}
          delete-branch: true

  cleanup-dev-dependencies:
    needs: [setup]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        value: ${{fromJson(needs.setup.outputs.devDependencies_matrix)}}
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v3
      - name: Npm remove
        run: |
          cd test/
          npm remove ${{ matrix.value }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          committer: GitHub <noreply@github.com>
          commit-message: Remove unused dev dependency ${{ matrix.value }}
          title: Remove unused dev dependency ${{ matrix.value }}
          body: 
          branch: depcheck/remove-dev-dependency-${{ matrix.value }}
          delete-branch: true
  