name: Check dependencies

on:
  push: # for testing purposes, remove before merge
    branches:
    - "main"
  schedule:
    - cron: '0 0 * * 1'
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.depcheck_dependencies }}
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v3
      - name: Check node dependencies
        id: depcheck
        uses: ./.github/actions/depcheck/
        with:
          dir: test/
      - id: matrix
        name: Get unused dependencies
        run: |
          echo "depcheck_dependencies=\"${{ steps.depcheck.outputs.unused_json }}\" | jq '.dependencies[]'" >> $GITHUB_ENV
          # echo "devcheck_devDependencies\"${{ steps.depcheck.outputs.unused_json }}\" | jq '.devDependencies[]'" >> $GITHUB_ENV

  cleanup:
    needs: [setup]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        value: ${{fromJson(needs.setup.outputs.matrix)}}
    steps:
      - name: remove unused dependencies
        uses: stevensnoeijen/depcheck-workflow/.github/workflows/npm-dependency-remove.yml@main
        with:
          dependency: "${{ matrix.value }}"
