name: Check dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.depcheck_dependencies }}
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v3
      - name: Check node dependencies
        id: depcheck
        uses: ./.github/actions/depcheck
        with:
          dir: test/
      - id: matrix
        name: Get unused dependencies
        run: |
          dependencies=$(echo ${{ steps.depcheck.outputs.result_json }} | jq '.dependencies' -c)
          echo "depcheck_dependencies=$dependencies" >> $GITHUB_OUTPUT
          # echo "devcheck_devDependencies\"${{ steps.depcheck.outputs.result_json }}\" | jq '.devDependencies'" >> $GITHUB_OUTPUT

  cleanup:
    needs: [setup]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        value: ${{fromJson(needs.setup.outputs.matrix)}}
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v3
      - name: Npm remove
        run: |
          cd test/
          npm remove ${{ matrix.value }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          committer: GitHub <noreply@github.com>
          commit-message: Remove dependency ${{ matrix.value }}
          title: Remove dependency ${{ matrix.value }}
          body: 
          branch: depcheck/remove-dependency-${{ matrix.value }}
          delete-branch: true

  